version: '3.4'
services:

  server:
    restart: always
    ports:
      - "50051:50051"
    build:
      dockerfile: greet/greet_server/Dockerfile
      context: .

  client:
    network_mode: host
    restart: always
    depends_on:
      - server
    build:
      dockerfile: greet/greet_client/Dockerfile
      context: .